### ISSUE TITLE
Inception: Flows

### ISSUE THREAD

**Issue by roalcantara** [tango-crew/tango#2]
- Define all the main flows:
- Create grafic workflow for each flow;

**Comment by saulocamposi** [comment]
First Step : Preview of App
![main](https://cloud.githubusercontent.com/assets/5776988/10616806/d40ee796-7745-11e5-8d6a-4d295ed61a96.png)

Second Step : Sign Up or Sign In 
![page1](https://cloud.githubusercontent.com/assets/5776988/10616807/d4501fea-7745-11e5-9b5f-00ab33bf839b.png)

Third Step : User choose your profile type
![page2](https://cloud.githubusercontent.com/assets/5776988/10616808/d45062d4-7745-11e5-85ba-c67dbdfc843f.png)


![page3](https://cloud.githubusercontent.com/assets/5776988/10616809/d456573e-7745-11e5-81a9-9e00ac1dc1ea.png)
![page4](https://cloud.githubusercontent.com/assets/5776988/10616810/d4583f86-7745-11e5-8f5b-3d4941a022e7.png)

**Comment by saulocamposi** [comment]
First Step : Preview of App

![main](https://cloud.githubusercontent.com/assets/5776988/10617133/961195f4-7747-11e5-92bc-7dd0d8094c67.png)
------------------------------------------------------------------------------------------------------------------------------
Second Step : Sign Up or Sign In 

![page1](https://cloud.githubusercontent.com/assets/5776988/10617136/97204490-7747-11e5-88a0-7c9c119633f3.png)
------------------------------------------------------------------------------------------------------------------------------
Third Step : User choose your profile type

![page2](https://cloud.githubusercontent.com/assets/5776988/10617137/972f4cec-7747-11e5-95bc-016f79c766c9.png)
------------------------------------------------------------------------------------------------------------------------------
Fourth Step : Profile HairDresser

![page3](https://cloud.githubusercontent.com/assets/5776988/10617138/973ad6d4-7747-11e5-8da7-2e24eb434729.png)
------------------------------------------------------------------------------------------------------------------------------
Fifth Step: Timeline HairDresser

![page4](https://cloud.githubusercontent.com/assets/5776988/10617139/973c3c2c-7747-11e5-9d13-578b51d104e4.png)

**Comment by saulocamposi** [comment]
Main Timeline

![page5](https://cloud.githubusercontent.com/assets/5776988/10617338/bb1351c0-7748-11e5-93bf-3f03277cfece.png)

-------------------------------------------------------------------------------------------------------------------------------

Search HairDresser

![page6](https://cloud.githubusercontent.com/assets/5776988/10617353/d7529472-7748-11e5-8404-662a3691161b.png)

**Comment by saulocamposi** [comment]
Publishing work

![publishtango](https://cloud.githubusercontent.com/assets/5776988/10671918/f6f2618e-78cb-11e5-8ca2-3d5f88e94e6f.png)

------------------------------------------------------------------------------------------------------------------------------

Main Page Tango 2 

![publishtango](https://cloud.githubusercontent.com/assets/5776988/10671984/33b694b4-78cc-11e5-9cc2-7c93bd3c08bb.png)

**Comment by saulocamposi** [comment]
Galera segue o protótipo funcional utilizando o ioniccreator

https://creator.ionic.io/share/1944e359c6e2

**Comment by roalcantara** [comment]
Muito bacana o protótipo funcional, Saulo! To cada vez mais animado!!! Vai ficar animal!!! :D

**Comment by ddomingues** [comment]
:+1: :100:
